<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error 
from sklearn.metrics import r2_score
import numpy as np

In [2]:
data = pd.read_csv('/Users/artemmm/Downloads/insurance.csv')

In [3]:
data.head()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [5]:
data.isna().sum()

Пол                  0
Возраст              0
Зарплата             0
Члены семьи          0
Страховые выплаты    0
dtype: int64

In [6]:
data['Возраст'].unique()

array([41., 46., 29., 21., 28., 43., 39., 25., 36., 32., 38., 23., 40.,
       34., 26., 42., 27., 33., 47., 30., 19., 31., 22., 20., 24., 18.,
       37., 48., 45., 44., 52., 49., 35., 56., 65., 55., 57., 54., 50.,
       53., 51., 58., 59., 60., 61., 62.])

In [7]:
data = data.astype({'Возраст':int})
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   int64  
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(1), int64(4)
memory usage: 195.4 KB


На первый взгляд данные в порядке.

## Умножение матриц

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Ответьте на вопрос и обоснуйте решение. 

Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? (Её можно обучить заново.)

a. Изменится. Приведите примеры матриц.

b. Не изменится. Укажите, как связаны параметры линейной регрессии в исходной задаче и в преобразованной.

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** Нет, не изменится.

**Обоснование:** Код ниже. Как мы видим - метрика примерно одинаковая до и после умножения.

* Думаю, что линейная регрессия может обучаться и находить веса, даже в умноженной матрице. 
* Также умножение на матрицу не изменяет сами зависимости между признаками, а просто переводит в другую "форму".

У нас есть возможность перевести матрицу из умноженой в обычную, умножив ее на обратную матрицу второго множителя.

Математическое обоснование:
$$
w' = (P^T X^T X P)^{-1} (XP)^T y
$$
    
А теперь поставим скобочки чтобы лучше было видно: 
    
    
$$
w' = (P^T (X^T X) P)^{-1} P^T X^T y
$$    

$$
w' = p^{-1} (X^{T}X)^{-1} (P^{t})^{-1} P{T}X{T}y =
$$

$$
w = (X^{T}X)^{-1} X^{T} y, поэтому
$$

$$
w' = P^{-1}w
$$

$$
Соотношение между wp и w:
$$


$$
XP w_p = X w
$$

$$
XPw*p^{-1} = Xw * p$$
**Как связаны параметры линейной регрессии в исходной задаче и преобразованной:** В исходной задаче и в преобразованной параметры имеют одни и те же зависимости и веса, только в "разных системах координат". Грубо говоря, в преобразованной матрице все параметры показаны в неизвестных нам величинах, но сами значения не изменялись.

## Алгоритм преобразования

**Алгоритм**

Создавать рандомную матрицу, перемножать матрицу признаков на созданную матрицу. Главные условия рандомной матрицы - она должна быть обратимой и размерность должна быть: кол-во строк = кол-во столбцов.


**Обоснование**

Их произведение получится умноженная матрица с теми же самыми зависимостями, только в другой форме. Данный способ основывается на том, что для восстановления изначальной информации нужна обратная матрица первого множителя, т.е. созданной матрицы. Это гарантирует проблемы при восстановлении исходных данных, ведь не имея рандомной матрицы будет тяжело перевести матрицу произведения в исходную матрицу.

## Проверка алгоритма

Алгоритм линейной регрессии.

In [8]:
class LinearRegression:
    def fit(self, train_features, train_target):
        X = np.concatenate((np.ones((train_features.shape[0], 1)), train_features), axis=1)
        y = train_target
        w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
        self.w = w[1:]
        self.w0 = w[0]

    def predict(self, test_features):
        return test_features.dot(self.w) + self.w0


Рандомная матрица.

In [9]:
import numpy as np
np.set_printoptions(suppress = True) 
#создаем матрицу
matr = np.random.randint(1,50, size=(data.shape[1] - 1 ,data.shape[1] - 1))
#проверяем на обратимость
matr_inv = np.linalg.inv(matr)
print(np.dot(matr, matr_inv))

[[ 1.  0. -0.  0.]
 [-0.  1. -0.  0.]
 [-0.  0.  1.  0.]
 [ 0. -0.  0.  1.]]


Перемножение матриц

In [10]:
#обучение линейной регрессии до умножения
df, test = train_test_split(data, test_size= 0.25, random_state = 12345)
df_t = df['Страховые выплаты']
df_f = df.drop('Страховые выплаты', axis = 1)

tr_t = test['Страховые выплаты']
tr_f = test.drop('Страховые выплаты', axis = 1)
pered_u = []
for i in range(5):
    model = LinearRegression()
    model.fit(df_f.values, df_t.values)
    predictions = model.predict(tr_f)
    pered_u.append(r2_score(tr_t, predictions))
print('До умножения:', sum(pered_u)/len(pered_u))

#coef1 = model.coef_

#умножение и обучение
df, test = train_test_split(data, test_size= 0.25)
df_t = df['Страховые выплаты']
df_f = df.drop('Страховые выплаты', axis = 1)

tr_t = test['Страховые выплаты']
tr_f = test.drop('Страховые выплаты', axis = 1)
df_f = df_f.values @ matr

tr_f = tr_f.values @ matr

posle_u = []
for i in range(5):
    model = LinearRegression()
    model.fit(df_f, df_t.values)
    predictions = model.predict(tr_f)
    posle_u.append(r2_score(tr_t, predictions))
print('После умножения:', sum(posle_u)/len(posle_u))

#coef2 = model.coef_

#print(coef1 / (coef2 @ matr_inv))

До умножения: 0.43522757127026657
После умножения: 0.346160613845519


In [11]:
train, test = train_test_split(data, test_size= 0.25)
X = train.drop('Страховые выплаты', axis = 1).values
y = train['Страховые выплаты'].values

X_t = test.drop('Страховые выплаты', axis = 1).values
y_t = test['Страховые выплаты'].values
w = np.linalg.inv((X.T@X))@X.T@y
print(w)
y_hat = X@w
print(r2_score(y, y_hat))

np.random.seed(1)
matr = np.random.randn(4,4)
X_m = X@matr
inv_matr = np.linalg.inv(matr)

w_m = np.linalg.inv((X_m.T@X_m))@X_m.T@y
print(w_m)
y_hat_m = X_m@w_m
print(r2_score(y, y_hat_m))

[-0.03631314  0.02358289 -0.00001201 -0.04578236]
0.3099772375620381
[0.13655643 0.11219784 0.14062875 0.10737832]
0.3099772375614255


Чтобы перевести преобразованные данные в исходные, нужно умножить преобразованную матрицу на матрицу обратную второму множителю.

In [12]:
print(X_m)
print('/')
print(X_m @ inv_matr)

[[   7815.27973135   -6163.88528811   35735.36286157  -50295.48720626]
 [  14383.26454187  -11293.39865044   65850.08010116  -92731.02923259]
 [  16832.39933005  -13192.45263899   77091.47414108 -108586.16194235]
 ...
 [  15271.38156506  -11977.8264696    69933.5134543   -98494.85597778]
 [  11683.1190451    -9202.36473401   53443.70597514  -75231.14054456]
 [   8446.86354953   -6647.82099612   38648.50426739  -54409.02852396]]
/
[[    1.    34. 24400.     1.]
 [   -0.    31. 45000.     1.]
 [   -0.    22. 52700.    -0.]
 ...
 [   -0.    25. 47800.     1.]
 [    1.    43. 36500.     2.]
 [   -0.    28. 26400.    -0.]]


**Итог проекта:**

Задача проекта: Защитить данные клиентов страховой компании «Хоть потоп». Разработать такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обосновать корректность его работы.

В ходе проекта:
* Загрузил и изучил данные, исправил типы столбцов.
* Ответил на вопрос: "Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? "
* Обосновал ответ на вопрос в практической форме (сделав код) и теоретической (формулами).
* Предложил алгоритм преобразования данных для решения задачи.
* Запрограммировал алгоритм.

Кратко: оказалось, что качество регрессии не изменяется, если матрицу признаков умножить на любую обратимую матрицу, воспользовавшись этим, я придумал алгоритм перевода исходной матрицы признаков в матрицу признаков "другого измерения". То есть, не имея матрицы признаков получить исходные данные очень сложно. После чего запрограммировал этот алгоритм. Он доказал, что качество линейной регрессии не изменилось. 

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [x]  Весь код выполняется без ошибок
- [x]  Ячейки с кодом расположены в порядке исполнения
- [x]  Выполнен шаг 1: данные загружены
- [x]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [x]  Указан правильный вариант ответа
    - [x]  Вариант обоснован
- [x]  Выполнен шаг 3: предложен алгоритм преобразования
    - [x]  Алгоритм описан
    - [x]  Алгоритм обоснован
- [x]  Выполнен шаг 4: алгоритм проверен
    - [x]  Алгоритм реализован
    - [x]  Проведено сравнение качества моделей до и после преобразования